export const FUNCTIONS = [
  'count',
  'covariance',
  'cumulativeSum',
  'derivative',
  'difference',
  'distinct',
  'filter',
  'first',
  'from',
  'group',
  'integral',
  'join',
  'last',
  'limit',
  'map',
  'max',
  'mean',
  'min',
  'percentile',
  'range',
  'sample',
  'set',
  'shift',
  'skew',
  'sort',
  'spread',
  'stateTracking',
  'stddev',
  'sum',
  'window',
  'yield',
];

const tokenizer = {
  comment: {
    pattern: /(^|[^\\:])\/\/.*/,
    lookbehind: true,
    greedy: true,
  },
  string: {
    pattern: /(["'])(?:\\(?:\r\n|[\s\S])|(?!\1)[^\\\r\n])*\1/,
    greedy: true,
  },
  builtin: new RegExp(`\\b(?:${FUNCTIONS.join('|')})(?=\\s*\\()`, 'i'),
  keyword: /\b(?:and|empty|import|in|not|or|return)\b/,
  boolean: /\b(?:true|false)\b/,
  function: /[a-z0-9_]+(?=\()/i,
  number: /\b0x[\da-f]+\b|(?:\b\d+\.?\d*|\B\.\d+)(?:e[+-]?\d+)?/i,
  operator: /-|\+|\*|\/|%|==|<=?|>=?|!=|!~|=~|=|<-|\|>/,
  punctuation: /[{}[\];(),.:]/,
};

export default tokenizer;
